### ISSUE TITLE
请问使用的是什么浏览器？“保存以备替代”这个没找到

### ISSUE THREAD

**Issue by xuanjinya** [Edison-cgx/smartedu#1]
请问使用的是什么浏览器？“保存以备替代”这个没找到

**Comment by Edison-cgx** [comment]
![QQ截图20240207181205](https://github.com/Edison-cgx/smartedu/assets/140296586/270bf3d7-2ea8-492d-92bb-7128f3f6e88c)
我一直用微软的edge浏览器，最新版本的名称已经不同了。你看看你的浏览器这个叫什么~
### 不过这个方法已经失效了，开了倍速也没用了
